version: '3.9'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todolist
    volumes:

      - ./volume:/var/lib/postgresql/data

    ports:
      - "5432:5432"
volumes:
  postgres_data: